#!/bin/bash
set -e
wget -qO /tmp/debian-custom/config/hooks/normal/00-am.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/am.sh
#wget -qO /tmp/debian-custom/config/hooks/normal/armcord.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/armcord.sh
wget -qO /tmp/debian-custom/config/hooks/normal/bat.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/bat.sh
wget -qO /tmp/debian-custom/config/hooks/normal/calamares.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/calamares.sh
wget -qO /tmp/debian-custom/config/hooks/normal/casterr.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/casterr.sh
wget -qO /tmp/debian-custom/config/hooks/normal/cfs-zen-tweaks.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/cfs-zen-tweaks.sh
wget -qO /tmp/debian-custom/config/hooks/normal/custom-user-settings.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/custom-user-settings.sh
wget -qO /tmp/debian-custom/config/hooks/normal/extra-repositories.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/extra-repositories.sh
wget -qO /tmp/debian-custom/config/hooks/normal/fd.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/fd.sh
wget -qO /tmp/debian-custom/config/hooks/normal/flathub.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/flathub.sh
wget -qO /tmp/debian-custom/config/hooks/normal/fluent-gtk.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/fluent-gtk.sh
wget -qO /tmp/debian-custom/config/hooks/normal/freetube.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/freetube.sh
wget -qO /tmp/debian-custom/config/hooks/normal/gnome-shell-extensions.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/gnome-shell-extensions.sh
#wget -qO /tmp/debian-custom/config/hooks/normal/grub-settings.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/grub-settings.sh
wget -qO /tmp/debian-custom/config/hooks/normal/jack.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/jack.sh
wget -qO /tmp/debian-custom/config/hooks/normal/kernel.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/kernel.sh
wget -qO /tmp/debian-custom/config/hooks/normal/keybase.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/keybase.sh
#wget -qO /tmp/debian-custom/config/hooks/normal/lightdm.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/lightdm.sh
wget -qO /tmp/debian-custom/config/hooks/normal/mission-center.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/mission-center.sh
wget -qO /tmp/debian-custom/config/hooks/normal/plymouth.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/plymouth.sh
wget -qO /tmp/debian-custom/config/hooks/normal/protonvpn.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/protonvpn.sh
wget -qO /tmp/debian-custom/config/hooks/normal/purge.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/purge.sh
wget -qO /tmp/debian-custom/config/hooks/normal/rtcqs.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/rtcqs.sh
wget -qO /tmp/debian-custom/config/hooks/normal/rustdesk.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/rustdesk.sh
wget -qO /tmp/debian-custom/config/hooks/normal/topgrade.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/topgrade.sh
wget -qO /tmp/debian-custom/config/hooks/normal/virtualbox-x11.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/virtualbox-x11.sh
wget -qO /tmp/debian-custom/config/hooks/normal/x11.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/x11.sh
wget -qO /tmp/debian-custom/config/hooks/normal/zap.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/zap.sh
wget -qO /tmp/debian-custom/config/hooks/normal/zen-browser.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/zen-browser.sh
wget -qO /tmp/debian-custom/config/hooks/normal/zz-alsa-firmware.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/alsa-firmware.sh
wget -qO /tmp/debian-custom/config/hooks/normal/zz-clean-root.hook.chroot https://github.com/rauldipeas/debian-custom/raw/main/scripts/clean-root.sh