name: Debian
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'leiame.md'
      - 'readme.md'
      - 'to-do.log'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
      - 'assets'
      - 'scripts'
      - 'settings'
      - '.github/workflows/debian-custom.yml'
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branches: pages